#!/bin/bash
# Clone or pull niceday-components
# Niceday components depend on 'goalie-js', which is a private repository.
# Thus, we cannot directly build it from github, so we clone it locally to build from there.
if cd build/niceday-components
then git pull
else git clone https://github.com/PerfectFit-project/niceday-components.git build/niceday-components
fi

cd build/niceday-components/niceday-broker/ || exit 1
./script/bootstrap
cd ..

cd niceday-api/ || exit 1
./script/bootstrap
cd ..
